### ISSUE TITLE
Issue with BERN file "normalization.tar.gz" while setting NEN server: archive contains contents of "GNormPlusJava.tar.gz" instead

### ISSUE THREAD

**Issue by aatif1992** [jacobvsdanniel/pubmedkb_core#2]
While setting up NEN server, one required BERN file "normalization.tar.gz" is containing the same contents as of GNormPlusJava.tar.gz. It appears as if its contents are incorrectly archived. Can you please confirm and place the "normalization" files on Google Drive?

Thanks.

**Comment by jacobvsdanniel** [comment]
We updated normalization.tar.gz on Google Drive just now.

**Comment by aatif1992** [comment]
Thanks a lot!
